StudentAttendence/Models/Attendence.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace StudentAttendence.Models
{
    public class Attendence
    {
        
        [Key]
        public int AttendenceID { get; set; }

        [ForeignKey("Student")]
        public int StudentID { get; set; }

        
        [ForeignKey("Timetable")]
        public int TimetableID { get; set; }
        
        [Required]
        public DateTime Date { get; set; }

        [Required]
        public string Condition { get; set; }

        public Attendence() { }

        public Attendence(int studentID, int timetableID, DateTime date, string condition)
        {
            StudentID = studentID;
            TimetableID = timetableID;
            Date = date;
            Condition = condition;
        }

        public virtual Timetable Timetable { get; set; }
        public virtual Student Student { get; set; }
    }
}

StudentAttendence/Controllers/AttendencesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentAttendence.Models;

namespace StudentAttendence.Controllers
{
    [Authorize(Roles = "Admin,  Student_Service, Teacher")]
    public class AttendencesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Attendences
        public ActionResult Index()
        {
            var studentAttendence = db.GetStudentAttendence();
            ViewBag.GroupID = new SelectList(db.GetGroup(), "GroupID", "GroupID");
            ViewBag.TimetableID = new SelectList((from timetable in db.GetModuleTimetable().ToList()
            select new
            {
                TimetableID = timetable.TimeTableId,
                TimetableValue = timetable.ModuleName + " " + timetable.Day + " " + timetable.ClassStartTime + " " + timetable.ClassEndTime
            }),"TimetableID","TimetableValue");

            return View(studentAttendence.ToList());
        }

        public ActionResult FilterIndex(string groupId, int timetableID)
        {
            var studentAttendence = db.GetStudentAttendence(groupId, timetableID);

            ViewBag.GroupID = new SelectList(db.GetGroup(), "GroupID", "GroupID");

            List<ModuleTimetableBridge> timetableList = db.GetModuleTimetable();
            ViewBag.TimetableID = new SelectList((from timetable in timetableList
                                                       select new
                                                  {
                                                      TimetableID = timetable.TimeTableId,
                                                      TimetableValue = timetable.ModuleName + " " + timetable.Day + " " + timetable.ClassStartTime + " " + timetable.ClassEndTime
                                                  }), "TimetableID", "TimetableValue");

            if (timetableList.Count > 0) {
                ViewBag.ModuleName = timetableList[0].ModuleName;
            }            
            ViewBag.GroupName = groupId;
            return View(studentAttendence.ToList());
        }

        // GET: Attendences/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentsAttendence studentAttendence = db.GetStudentAttendence(id);
            if (studentAttendence == null)
            {
                return HttpNotFound();
            }
            return View(studentAttendence);
        }

        

        // GET: Attendences/Create
        public ActionResult Create(string groupID)
        {
            ViewBag.StudentID = new SelectList((from student in db.GetStudent()
                                                select new
                                                {
                                                    StudentID = student.StudentID,
                                                    StudentName = student.FirstName + " " + student.LastName
                                                }), "StudentID", "StudentName");
            ViewBag.TimetableID = new SelectList((from timetable in db.GetModuleTimetable()
                                                  select new
                                                  {
                                                      TimetableID = timetable.TimeTableId,
                                                      TimetableValue = timetable.ModuleName + " " + timetable.Day + " " + timetable.ClassStartTime + " " + timetable.ClassEndTime
                                                  }), "TimetableID", "TimetableValue");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AttendencePage(string groupID, int timetableID) {
            List<Student> studentList = db.GetGroupStudent(groupID);
            Timetable timetable = db.GetTimetable(timetableID);
            Module module = db.GetModule(timetable.ModuleID);
            List<StudentsAttendence> studentsAttendenceList = new List<StudentsAttendence>();
            foreach (Student student in studentList) {
                StudentsAttendence studentAttendence = new StudentsAttendence( student.StudentID, timetable.TimeTableId, student.FirstName, student.LastName, timetable.ClassStartTime, timetable.ClassEndTime, module.ModuleName, DateTime.Now, "p");
                studentsAttendenceList.Add(studentAttendence);
            }
            ViewBag.ModuleName = module.ModuleName;
            ViewBag.ClassStartTime = timetable.ClassStartTime;
            ViewBag.ClassEndTime = timetable.ClassEndTime;
            ViewBag.Date = DateTime.Now;

            return View(studentsAttendenceList);
        }

        // POST: Attendences/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( List<StudentsAttendence> studentAttendenceList)
        {
            if (ModelState.IsValid)
            {
                foreach(StudentsAttendence studentAttendence in studentAttendenceList){
                    Attendence attedence = new Attendence(studentAttendence.StudentID, studentAttendence.TimetableID, studentAttendence.Date, studentAttendence.Condition);
                    db.CreateAttendence(attedence);
                }
                return RedirectToAction("Index");
            }
            return RedirectToAction("AttendencePage");
        }

        // GET: Attendences/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attendence attendence = db.GetAttendence(id);
            if (attendence == null)
            {
                return HttpNotFound();
            }
            ViewBag.StudentID = new SelectList((from student in db.GetStudent()
                                                select new
                                                {
                                                    StudentID = student.StudentID,
                                                    StudentName = student.FirstName + " " + student.LastName
                                                }), "StudentID", "StudentName" ,attendence.StudentID);
            ViewBag.TimetableID = new SelectList((from timetable in db.GetModuleTimetable()
                                                  select new
                                                  {
                                                      TimetableID = timetable.TimeTableId,
                                                      TimetableValue = timetable.ModuleName + " " + timetable.Day + " " + timetable.ClassStartTime + " " + timetable.ClassEndTime
                                                  }), "TimetableID", "TimetableValue", attendence.TimetableID);

            return View(attendence);
        }

        // POST: Attendences/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AttendenceID,StudentID,TimetableID,Date,Condition")] Attendence attendence)
        {
            if (ModelState.IsValid)
            {
                db.UpdateAttendence(attendence);
                return RedirectToAction("Index");
            }
            return View(attendence);
        }

        // GET: Attendences/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentsAttendence studentAttendence = db.GetStudentAttendence(id);
            if (studentAttendence == null)
            {
                return HttpNotFound();
            }
            return View(studentAttendence);
        }

        // POST: Attendences/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.DeleteAttendence(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentAttendence/Views/Attendences/AttendencePage.cshtml
@model IList<StudentAttendence.Models.StudentsAttendence>

@{
    ViewBag.Title = "Index";
    var ModuleName = ViewData["ModuleName"];
    var ClassStartTime = ViewData["ClassStartTime"];
    var ClassEndTime = ViewData["ClassEndTime"];
    var Date = ViewData["Date"];
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Student Attendece</strong>
            </div>
            <div class="card-body">
                <table>
                    <tr>
                        <th>Date</th>
                        <td>
                            @DateTime.Now.ToString("MM/dd/yyyy")
                        </td>
                    </tr>
                    <tr>
                        <th>Module</th>
                        <td>@ModuleName</td>
                    </tr>
                    <tr>
                        <th>Time</th>
                        <td>
                           
                            @ClassStartTime To @ClassEndTime
                        </td>
                    </tr>
                </table>
                @using (Ajax.BeginForm("Create", "Attendences", new AjaxOptions { UpdateTargetId = "attendenceList" }))
                {
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">S.N.</th>
                                <th scope="col">Name</th>
                                <th scope="col">Status</th>
                            </tr>
                        </thead>

                        @Html.AntiForgeryToken()
                        <tbody id="attendenceList">
                            @{ int counter = 0; }
                            @for (int i = 0; i < Model.Count; i++)
                            {
                                counter = counter + 1;
                                <tr>
                                    @Html.HiddenFor(model => Model[i].StudentID)
                                    @Html.HiddenFor(model => Model[i].TimetableID)
                                    @Html.HiddenFor(model => Model[i].Date)

                                    <td>@counter</td>
                                    <td>@Html.DisplayFor(model => Model[i].FirstName) @Html.DisplayFor(model => Model[i].LastName)</td>
                                    <td>
                                        <text>
                                            @Html.RadioButtonFor(modelItem => Model[i].Condition, "Present", new { @checked = true })
                                            @Html.Label("Present")

                                            @Html.RadioButtonFor(modelItem => Model[i].Condition, "Late")
                                            @Html.Label("Late")

                                            @Html.RadioButtonFor(modelItem => Model[i].Condition, "Absent")
                                            @Html.Label("Absent")
                                        </text>
                                    </td>
                                </tr>

                            }
                        </tbody>

                    </table>
                    <div class="card-footer">
                        <div class="form-actions">
                            <span>Submit this Record? </span>
                            <div class="btn">
                                <input type="submit" class="btn btn-sm btn-outline-primary" value="Yes" />
                            </div>
                            @Html.ActionLink("Back to Index Page", "Index")
                        </div>
                    </div>
                }
            </div>
        </div>
     </div>   
 </div>

StudentAttendence/Views/Attendences/Create.cshtml
@model StudentAttendence.Models.Attendence

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Attendence</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentID, "StudentID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimetableID, "TimetableID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TimetableID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TimetableID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Condition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Condition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Condition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentAttendence/Views/Attendences/Delete.cshtml
@model StudentAttendence.Models.StudentsAttendence

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Attendence</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Condition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Condition)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StudentAttendence/Views/Attendences/Details.cshtml
@model StudentAttendence.Models.StudentsAttendence

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Attendence</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Condition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Condition)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StudentAttendence/Views/Attendences/Edit.cshtml
@model StudentAttendence.Models.Attendence

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Attendence</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.StudentID)

    @Html.HiddenFor(model => model.TimetableID)
    @Html.HiddenFor(model => model.AttendenceID)

    
    <div class="form-group">
        @Html.LabelFor(model => model.StudentID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("StudentID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StudentID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TimetableID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TimetableID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Condition, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Condition, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Condition, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentAttendence/Views/Attendences/Index.cshtml
@model IEnumerable<StudentAttendence.Models.StudentsAttendence>

@{
    ViewBag.Title = "Index: Student Attendence";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <strong class="card-title"> Student Attendence </strong>
            </div>
            <div class="card-body">
                <b>Start Attendence</b>
                <div class="" id="start_attendence" style="border-style: solid; padding-left: 99px; border-width: inherit;">
                    @using (Ajax.BeginForm("AttendencePage", "Attendences", new AjaxOptions { UpdateTargetId = "result" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="row form-group">
                            <div class="col col-md-2">
                                <label for="text-input" class=" form-control-label">Group ID</label>
                            </div>
                            <div class="col-md-2">
                                @Html.DropDownList("GroupID", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                            <div class="col col-md-2">
                                <label for="text-input" class=" form-control-label">Timetable ID</label>
                            </div>

                            <div class="col-md-3">
                                @Html.DropDownList("TimetableID", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                            <div class="col-md-2">
                                <div class="class=" btn btn-outline-success"">
                                    <button type="submit" value="Start Attendence" class="btn btn-outline-primary"> <i class="fa fa-location-arrow"></i> Start Attendence</button>
</div>
                            </div>
                        </div>

                    }
                </div>
                <hr />
                <b>Filter Attendence</b>
                <div class="" id="" style="border-style: solid; padding-left: 99px; border-width: inherit;">
                    @using (Ajax.BeginForm("FilterIndex", "Attendences", new AjaxOptions { UpdateTargetId = "result" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="row form-group">
                            <div class="col col-md-2">
                                <label for="text-input" class=" form-control-label">Group ID</label>
                            </div>
                            <div class="col-md-2">
                                @Html.DropDownList("GroupID", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                            <div class="col col-md-2">
                                <label for="text-input" class=" form-control-label">Timetable ID</label>
                            </div>

                            <div class="col-md-3">
                                @Html.DropDownList("TimetableID", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                            <div class="col-md-2">
                                <div class="class=" btn btn-outline-success"">
                                    <button type="submit" value="View Attendence" class=" btn btn-outline-info"><i class="fa fa-filter"></i> View Attendence</button>
                                </div>
                            </div>
                        </div>

                    }
                </div>
                <hr />
                <b> Attendence Records </b>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">S.N.</th>
                            <th scope="col">Name</th>
                            <th scope="col">Date</th>
                            <th scope="col">Class Start time</th>
                            <th scope="col">Class End time</th>
                            <th scope="col">Module</th>
                            <th scope="col">Status</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ int counter = 0;
                            foreach (var item in Model)
                            {
                                counter = counter + 1;
                                                <tr>
                                                    <th scope="row">@counter</th>
                                                    <td>
                                                        @Html.HiddenFor(modelItem => item.StudentID)
                                                        @Html.DisplayFor(modelItem => item.FirstName) @Html.DisplayFor(modelItem => item.LastName)
                                                    </td>

                                                    <td>
                                                        @Html.HiddenFor(modelItem => item.Date)
                                                        @Html.HiddenFor(modelItem => item.TimetableID)
                                                        @Html.FormatValue("yyy-MM-dd", item.Date.ToString("yyy-MM-dd"))

                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.ClassStartTime)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.ClassEndTime)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.ModuleName)
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.Condition)
                                                    </td>

                                                    <td>
                                                        <div class="btn btn-outline-success">
                                                            <i class="fa fa-pencil"></i>
                                                            @Html.ActionLink("Edit", "Edit", new { id = item.ID })
                                                        </div>
                                                        <div class="btn btn-outline-info">
                                                            <i class="fa fa-eye"></i>
                                                            @Html.ActionLink("Details", "Details", new { id = item.ID })
                                                        </div>
                                                        <div class="btn btn-outline-danger">
                                                            <i class="fa fa-trash"></i>
                                                            @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                                                        </div>
                                                    </td>
                                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>