StudentAttendence/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentAttendence.Models;

namespace StudentAttendence.Controllers
{
    [Authorize(Roles = "Admin,  Student_Service")]
    public class GroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Groups
        public ActionResult Index()
        {
            var facultyGroupList = db.GetFacultyGroup();
            return View(facultyGroupList.ToList());
        }

        // GET: Groups/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FacultyGroup facultyGroup = db.GetFacultyGroup(id);
            if (facultyGroup == null)
            {
                return HttpNotFound();
            }
            return View(facultyGroup);
        }

        // GET: Groups/Create
        public ActionResult Create()
        {
            List<Faculty> facultyList = db.GetFaculty();
            ViewBag.FacultyID = new SelectList(facultyList, "FacultyID", "FacultyName");
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GroupID,CreateDate,FacultyID")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.CreateGroup(group);
                return RedirectToAction("Index");
            }

            List<Faculty> facultiesList = db.GetFaculty();

            ViewBag.FacultyID = new SelectList(facultiesList, "FacultyID", "FacultyName", group.FacultyID);
            return View(group);
        }

        // GET: Groups/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.GetGroup(id);
            if (group == null)
            {
                return HttpNotFound();
            }

            List<Faculty> facultiesList = db.GetFaculty();
            ViewBag.FacultyID = new SelectList(facultiesList, "FacultyID", "FacultyName", group.FacultyID);
            return View(group);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GroupID,CreateDate,FacultyID")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.UpdateGroup(group);
                return RedirectToAction("Index");
            }
 
            ViewBag.FacultyID = new SelectList(db.GetFaculty(), "FacultyID", "FacultyName", group.FacultyID);
            return View(group);
        }

        // GET: Groups/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FacultyGroup facultyGroup = db.GetFacultyGroup(id);
            if (facultyGroup == null)
            {
                return HttpNotFound();
            }
            return View(facultyGroup);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            db.DeleteGroup(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentAttendence/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentAttendence.Models;

namespace StudentAttendence.Controllers
{
    [Authorize(Roles = "Admin,  Student_Service")]
    public class RolesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Roles
        public ActionResult Index()
        {
            return View(db.GetRole().ToList());
        }

        // GET: Roles/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.GetRole(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // GET: Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RoleID,RoleName,Qualification")] Role role)
        {
            if (ModelState.IsValid)
            {
                db.CreateRole(role);
                return RedirectToAction("Index");
            }

            return View(role);
        }

        // GET: Roles/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.GetRole(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RoleID,RoleName,Qualification")] Role role)
        {
            if (ModelState.IsValid)
            {
                db.UpdateRole(role);
                return RedirectToAction("Index");
            }
            return View(role);
        }

        // GET: Roles/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.GetRole(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.DeleteRole(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentAttendence/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>

    <link rel="apple-touch-icon" href="https://i.imgur.com/QRAUqs9.png">
    <link rel="shortcut icon" href="https://i.imgur.com/QRAUqs9.png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css"> -->
    <link href="@Url.Content("~/Content/assets/css/cs-skin-elastic.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/assets/css/style.css")" rel="stylesheet" type="text/css" />
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="@Url.Content("~/Content/assets/js/main.js")" type="text/javascript"></script>

</head>
<body>
    <!-- Left Panel -->
    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">
            <div id="main-menu" class="main-menu collapse navbar-collapse">
                    @Html.Partial("sidebar")                   
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside><!-- /#left-panel -->
    <!-- Left Panel -->
    <!-- Right Panel -->

    <div id="right-panel" class="right-panel">

        <!-- Header-->
        <header id="header" class="header">
            <div class="top-left">
                <div class="navbar-header">
                    <a class="navbar-brand" href="./"><h3>Student Attendence</h3></a>                    
                    @if (Request.IsAuthenticated)
                    {
                        <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
                     }                    
                </div>
            </div>
            <div class="top-right">
                <div class="header-menu">                    
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </header><!-- /header -->
        <!-- Header-->

        <div class="content">
            <div class="animated fadeIn">
                @RenderBody()
            </div><!-- .animated -->
        </div><!-- .content -->

        <div class="clearfix"></div>
        <footer class="site-footer" style="bottom:0; position:fixed; width:100%;">
            <div class="footer-inner bg-white">
                <div class="row">
                    <div class="col-sm-6">
                        Copyright &copy; @DateTime.Now.Year - Student Attendence System
                    </div>
                </div>
            </div>
        </footer>
    </div><!-- /#right-panel -->
    <!-- Right Panel -->

    @RenderSection("scripts", required: false)
</body>
</html>

StudentAttendence/Views/Shared/actionAdmin.cshtml
@if (User.IsInRole("Admin"))
{
    <div class="" style="padding-bottom: 20px;">
        <i class="fa fa-plus btn btn-outline-primary">
            @Html.ActionLink("Add New Record", "Create")
        </i>
    </div>
}

StudentAttendence/Views/Shared/sidebar.cshtml
@{
    var isAdmin = User.IsInRole("Admin");
    var isTeacher = User.IsInRole("Teacher");
    var isStudentService = User.IsInRole("Student_Service");

}

@if (Request.IsAuthenticated)
{
<ul class="nav navbar-nav">
    <li class="menu-item">
        <a href="@Url.Action("Index", "Home")">
            <i class="menu-icon fa fa-home"></i>Home
        </a>
    </li>

    <li class="menu-item">
        <a href="@Url.Action("Index", "Attendences")">
            <i class="menu-icon fa fa-check-circle"></i> Attendences
        </a>
    </li>

    <li class="menu-item">
        <a href="@Url.Action("Index", "Report")">
            <i class="menu-icon fa fa-list-alt"></i>Report
        </a>
    </li>

    <li class="menu-item">
        <a href="@Url.Action("Index", "Students")">
            <i class="menu-icon fa fa-users"></i>Student
        </a>
    </li>

    <li class="menu-item">
        <a href="@Url.Action("Index", "ModuleGroups")">
            <i class="menu-icon fa fa-object-group"></i>Student Group Module 
        </a>
    </li>

    <li class="menu-item">
        <a href="@Url.Action("Index", "Modules")">
            <i class="menu-icon fa fa-book"></i>Modules
        </a>
    </li>

    <li class="menu-item">
        <a href="@Url.Action("Index", "GroupTimetables")">
            <i class="menu-icon fa fa-sitemap"></i>Group Timetables
        </a>
    </li>  


    @if (isAdmin || isStudentService)
    {
        <li class="menu-item">
            <a href="@Url.Action("Index", "Groups")">
                <i class="menu-icon fa fa-circle"></i>Student Group
            </a>
        </li>

        <li class="menu-item">
            <a href="@Url.Action("Index", "Faculty")">
                <i class="menu-icon fa fa-building-o"></i>Faculty
            </a>
        </li>

        <li class="menu-item">
            <a href="@Url.Action("Index", "Roles")">
                <i class="menu-icon fa fa-suitcase"></i>Roles
            </a>
        </li>

        <li class="menu-item">
            <a href="@Url.Action("Index", "Teachers")">
                <i class="menu-icon fa fa-user"></i>Teachers
            </a>
        </li>

        <li class="menu-item">
            <a href="@Url.Action("Index", "TeacherRoles")">
                <i class="menu-icon fa fa-tasks"></i>Teacher Roles
            </a>
        </li>

        <li class="menu-item">
            <a href="@Url.Action("Index", "Timetables")">
                <i class="menu-icon fa fa-calendar"></i>Timetables
            </a>
        </li>

        <li class="menu-item">
            <a href="@Url.Action("Index", "Semesters")">
                <i class="menu-icon fa fa-globe"></i>Semesters
            </a>
        </li>

    }
</ul>
}